repos:
  - repo: local
    hooks:
      - id: stash-all-files
        name: Stash all files including untracked files
        entry: git stash --keep-index --include-untracked
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Format code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        name: Replace line endings
      - id: detect-private-key
        name: Detect private keys
  - repo: local
    hooks:
      - id: check-cloudformation
        name: Check generated CloudFormation templates
        entry: poetry run ./copilot_helper.py check-cloudformation
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/myint/autoflake.git
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--force-single-line-imports]
  - repo: https://github.com/myint/docformatter.git
    rev: v1.7.2
    hooks:
      - id: docformatter
        args:
          [
            "--in-place",
            "--wrap-summaries=80",
            "--wrap-descriptions=80",
            "--pre-summary-newline",
          ]
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.78'
    hooks:
      - id: flynt
  - repo: local
    hooks:
      - id: docs
        name: Generate command docs
        entry: poetry run ./utils/create_command_docs.py --module=copilot_helper --cmd=copilot_helper --output=./commands/COMMANDS.md
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: check-tracked-files
        name: Check tracked file changes
        entry: git diff --name-status --exit-code
        language: system
        pass_filenames: false
        always_run: true
