repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Format code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        name: Replace line endings
      - id: detect-private-key
        name: Detect private keys
  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/myint/autoflake.git
    rev: v2.0.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--force-single-line-imports]
  - repo: https://github.com/myint/docformatter.git
    rev: v1.5.1
    hooks:
      - id: docformatter
        args:
          [
            "--in-place",
            "--wrap-summaries=80",
            "--wrap-descriptions=80",
            "--pre-summary-newline",
          ]
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.77'
    hooks:
      - id: flynt
