version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install poetry
      - poetry install

  build:
    commands:
      - echo Running tests...
      - pytest
