version: 0.2

phases:
  install:
    commands:
      - echo Setting local Python versions
      - pyenv versions | awk 'match($0, /[0-9]\.[0-9]+\.[0-9]+/) { print substr($0, RSTART, RLENGTH) }' | tac > .python-version
      - |
        echo Check we are using the latest installed Python 3.x
        python --version
      - echo Installing dependencies
      - pip install poetry
      - poetry install

  build:
    commands:
      - echo Leaving placeholder here for when we merge https://github.com/uktrade/copilot-tools/pull/309
