version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements/dev.txt
  
  build:
    commands:
      - echo Running tests...
      - pytest
