version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements-test.txt
  
  build:
    commands:
      - echo Running Tests blah blah blah balh
      - pytest
  
  post_build:
    commands:
      - echo Tests Complete