version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - curl -sSL https://install.python-poetry.org | python3 -
      - poetry install

  build:
    commands:
      - echo Running tests...
      - pytest
