version: 0.2

phases:
  install:
    commands:
      - echo Setting local Python versions
      - pyenv versions | awk 'match($0, /[0-9]\.[0-9]+\.[0-9]+/) { print substr($0, RSTART, RLENGTH) }' | tac > .python-version
      - |
        echo Check we are using the latest installed Python 3.x
        python --version
      - echo Installing dependencies
      - pip install poetry
      - poetry install

  build:
    commands:
      - echo Running unit tests
      - echo TEMPORARILY SKIPPED FOR DEVELOPMENT SPEED
      # - poetry run tox
      - pwd
      - ls -al
      - ./copilot_helper.py --version
      - echo Cloning demodjango
      - git clone git@github.com:uktrade/demodjango.git
