version: 0.2

phases:
  pre_build:
    commands:
      - echo "3.9" > .python-version
      - cd images/conduit/postgres
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/uktrade
      - SHORT_HASH=$(git rev-parse --short HEAD)
  build:
    commands:
      - echo Build started on `date`
      - echo Building postgres conduit Docker image...
      - docker build -t public.ecr.aws/uktrade/tunnel:postgres .
      - docker tag public.ecr.aws/uktrade/tunnel:postgres public.ecr.aws/uktrade/tunnel:postgres-$SHORT_HASH .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing postgres conduit Docker image...
      - docker push public.ecr.aws/uktrade/tunnel:postgres
      - docker push public.ecr.aws/uktrade/tunnel:postgres-$SHORT_HASH
