version: 0.2

env:
  shell: bash
  parameter-store:
    PYPI_TOKEN: "pypi-token"

phases:
  install:
    commands:
      - |
        echo Ensure we are using the latest installed Python 3.x
        pyenv global 3
        python --version
      - echo Setting local Python versions
      - pyenv versions | awk 'match($0, /[0-9]\.[0-9]+\.[0-9]+/) { print substr($0, RSTART, RLENGTH) }' > .python-version
      - echo Installing dependencies
      - pip install poetry
      - poetry install

  build:
    commands:
      - echo Running tests
      - poetry run tox
      - |
        VERSION=$(python utils/check_pypi.py --version)
        if ! python utils/check_pypi.py
        then
          echo Building Python package
          poetry build
          echo Publishing Python package ${VERSION}
          poetry config pypi-token.pypi ${PYPI_TOKEN}
          poetry publish
          echo Checking the package has reached PyPI
          python utils/check_pypi.py --max-attempts 20
        else
          echo ${VERSION} of the package has already been published
        fi
