[tool.black]
line-length = 119

[tool.poetry]
name = "dbt-copilot-tools"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "dbt_copilot_tools"}]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "1.26.31"
boto3-stubs = "1.26.148"
botocore = "1.29.31"
click = "8.1.3"
cloudfoundry-client = "1.34.1"
mypy-boto3-codebuild = "1.26.0.post1"
PyYAML = "6.0"
Jinja2 = "3.1.2"
schema = "0.7.5"
jsonschema = "4.17.3"

[tool.poetry.group.dev.dependencies]
moto = "^4.1.11"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
