[tool.black]
line-length = 100

[tool.poetry]
name = "dbt-copilot-tools"
version = "0.1.63"
description = "Set of tools to help transfer applications/services from GOV.UK PaaS to DBT PaaS augmenting AWS Copilot."
authors = ["Department for Business and Trade Platform Team <sre-team@digital.trade.gov.uk>"]
license = "MIT"
readme = "dbt_copilot_helper/README.md"
packages = [
    { include = "dbt_copilot_helper" },
    { include = "copilot_helper.py" }
]

[tool.poetry.scripts]
copilot-helper = "copilot_helper:copilot_helper"

[tool.poetry.dependencies]
Jinja2 = "3.1.2"
PyYAML = "6.0.1"
boto3 = "^1.28.24"
boto3-stubs = "^1.26.148"
botocore = "^1.29.31"
click = "^8.1.3"
cloudfoundry-client = "1.35.2"
jsonschema = "4.17.3"
mypy-boto3-codebuild = "^1.26.0.post1"
python = "^3.9"
schema = "0.7.5"
cfn-flip = "1.3.0"
aiohttp = "^3.8.4"
certifi = "^2023.07.22"
cryptography = "^41.0.3"
jinja2-simple-tags = "^0.5.0"
cfn-lint = "^0.80.2"
requests = "^2.31.0"
prettytable = "^3.9.0"

[tool.poetry.group.dev.dependencies]
moto = {extras = ["all"], version = "^4.1.12"}
pyfakefs = "^5.2.2"
pytest = "^7.3.1"
pytest-env = "^0.8.1"
tox = "^4.6.0"
pre-commit = "^3.3.3"
freezegun = "^1.2.2"
parameterized = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
