version: 0.2

env:
  git-credential-helper: yes
  parameter-store:
    SLACK_CHANNEL_ID: /codebuild/slack_oauth_channel
    SLACK_TOKEN: /codebuild/slack_oauth_token
  variables:
    COLOR: false
    CI: true

phases:
  build:
    commands:
      - /work/cli deploy --send-notifications
