version: 0.2

env:
  git-credential-helper: yes
  parameter-store:
    SLACK_CHANNEL_ID: /codebuild/slack_oauth_channel
    SLACK_TOKEN: /codebuild/slack_oauth_token
  variables:
    COLOR: false
    CI: true

phases:
  install:
    commands:
      # Install copilot
      - COPILOT_VERSION=`cat .copilot-version`
      - wget -q "https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v${COPILOT_VERSION}" -O copilot
      - chmod +x ./copilot
      - mv copilot /usr/bin/
  build:
    commands:
      - /work/cli deploy --send-notifications
