# {% version_info %}

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

Mappings:
  {{ addon_config.prefix }}EnvConfiguration:
{% for environment_name, config in addon_config.environments.items() %}
    {{ environment_name }}:
      EnableOpsCenter: {% if config.enable_ops_center %}true{% else %}false{% endif %}
{% endfor %}

Resources:
  {{ addon_config.prefix }}ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub "${App}-${Env}-group"
      Description: !Sub "Resource group for ${App} in ${Env} environment."
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          TagFilters:
            - Key: copilot-application
              Values:
                - !Sub "${App}"
            - Key: copilot-environment
              Values:
                - !Sub "${Env}"

  {{ addon_config.prefix }}ApplicationInsights:
    Type: AWS::ApplicationInsights::Application
    Properties:
      AutoConfigurationEnabled: true
      ResourceGroupName: !Ref {{ addon_config.prefix }}ResourceGroup
      OpsCenterEnabled: !FindInMap [{{ addon_config.prefix }}EnvConfiguration, !Ref Env, EnableOpsCenter]
