name: Pull request title validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:

  pull-request-title-validation:
    name: Pull request title validation
    runs-on: ubuntu-latest

    steps:
      - name: Pull request title validation
        uses:  ytanikin/PRConventionalCommits@1.1.0
        with:
          # Todo: Look at allowing the exclamation marks in ytanikin/PRConventionalCommits
          task_types: '["feat","feat!","fix","fix!","docs","docs!","test","test!","ci","ci!","refactor","refactor!","perf","perf!","chore","chore!","revert","revert!"]'
