name: Pull request title validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:

  pull-request-title-validation:
    name: Pull request title validation
    runs-on: ubuntu-latest

    steps:
#      - uses: beemojs/conventional-pr-action@v2

      - name: Pull request title validation
        uses:  ytanikin/PRConventionalCommits@v1
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'false'
