name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Test against Python ${PYTHON_VERSION}
        run: poetry run tox -e "py${PYTHON_VERSION/./}"
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
